### ISSUE TITLE
<AP> User Manual Update Online: RC500S

### ISSUE THREAD

**Issue by DOD-AP-Sales** [dod-taiwan/MISC#2]
Please update it online by June 9th.
The current user manual might mislead customers because of the incorrect settings:
- GPS Logging On/off: It cannot be turned off
- Time-Lapse: No such function
- Plate Stamp: Not available
- Flicker Reduction: Not available

**Comment by dod-pm1** [comment]
A updated version will be provided by 9th.
Further changes with new firmware will be updated if needed.
