### ISSUE TITLE
<AP> DOD Player PIP Functionality Is Disabled when using USB 2.0

### ISSUE THREAD

**Issue by DOD-AP-Sales** [dod-taiwan/MISC#5]
Model: RC500S
FW: 20170703
Issue: DOD Player PIP function can only be executed when using USB 3.0 instead of USB 2.0 
Please help include the above in the user manual if possible as what we discussed on Aug 14th.

**Comment by dod-pm1** [comment]
As discussed, will consider adding these info into the manual.
The reason being USB2.0 may be too slow to read 2 1080p video file to buffer for viewing.
But this is not a bug, simply similar to try to watch 5 movies at a same time from a external hard drive.
